#Ejercicio 2:

i. Hacer una matriz de 8 x 8 con numeros enteros consecutivos empezando en 1. Llenado por columnas.

ii. reemplazar los elementos que tengan al menos un 3 por -99.

In [318]:
import numpy as np

A, n = np.zeros((8,8)), 0

for i in range(len(A)):
  for j in range(len(A)):
    n = 1 + n
    A[i,j] = n
A = A.T
  
print("A = \n" , A)

A = 
 [[ 1.  9. 17. 25. 33. 41. 49. 57.]
 [ 2. 10. 18. 26. 34. 42. 50. 58.]
 [ 3. 11. 19. 27. 35. 43. 51. 59.]
 [ 4. 12. 20. 28. 36. 44. 52. 60.]
 [ 5. 13. 21. 29. 37. 45. 53. 61.]
 [ 6. 14. 22. 30. 38. 46. 54. 62.]
 [ 7. 15. 23. 31. 39. 47. 55. 63.]
 [ 8. 16. 24. 32. 40. 48. 56. 64.]]


In [319]:
for i in range(len(A)):
  for j in range(len(A)):
    for k in range(len(str(A[i,j]))):
      if str(A[i,j])[k] == '3':
        A[i,j] = -99 

print(A)

[[  1.   9.  17.  25. -99.  41.  49.  57.]
 [  2.  10.  18.  26. -99.  42.  50.  58.]
 [-99.  11.  19.  27. -99. -99.  51.  59.]
 [  4.  12.  20.  28. -99.  44.  52.  60.]
 [  5. -99.  21.  29. -99.  45. -99.  61.]
 [  6.  14.  22. -99. -99.  46.  54.  62.]
 [  7.  15. -99. -99. -99.  47.  55. -99.]
 [  8.  16.  24. -99.  40.  48.  56.  64.]]




#Ejercicio 3:

i. Reproducir la matriz B:

[[0.4 0.41 0.42 0.43 0.44]

[0.45 0.46 0.47 0.48 0.49]

[0.5 0.51 0.52 0.53 0.54]

[0.55 0.56 0.57 0.58 0.59]

[0.6 0.61 0.62 0.63 0.64]

[0.65 0.66 0.67 0.68 0.69]

[0.7 0.71 0.72 0.73 0.74]

[0.75 0.76 0.77 0.78 0.79]]

ii. Unir B con el resultado del ejercicio anterior 2.ii para obtener una matriz de 8 lineas y 13 columnas.

iii. Agregar una linea al final con el promedio de cada columna

iv. Agregar una columna al final con el valor maximo de cada fila

v. Guardar en un archivo.



In [320]:
B, n = np.zeros((8,5)), 0.4

for i in range(B.shape[0]):
  for j in range(B.shape[1]):
    B[i,j] = n
    n = .01 + n
  
print("B = \n" , B)

B = 
 [[0.4  0.41 0.42 0.43 0.44]
 [0.45 0.46 0.47 0.48 0.49]
 [0.5  0.51 0.52 0.53 0.54]
 [0.55 0.56 0.57 0.58 0.59]
 [0.6  0.61 0.62 0.63 0.64]
 [0.65 0.66 0.67 0.68 0.69]
 [0.7  0.71 0.72 0.73 0.74]
 [0.75 0.76 0.77 0.78 0.79]]


In [321]:
C = np.hstack((A, B))
print("C = \n" , C)
print(C.shape)

C = 
 [[  1.     9.    17.    25.   -99.    41.    49.    57.     0.4    0.41
    0.42   0.43   0.44]
 [  2.    10.    18.    26.   -99.    42.    50.    58.     0.45   0.46
    0.47   0.48   0.49]
 [-99.    11.    19.    27.   -99.   -99.    51.    59.     0.5    0.51
    0.52   0.53   0.54]
 [  4.    12.    20.    28.   -99.    44.    52.    60.     0.55   0.56
    0.57   0.58   0.59]
 [  5.   -99.    21.    29.   -99.    45.   -99.    61.     0.6    0.61
    0.62   0.63   0.64]
 [  6.    14.    22.   -99.   -99.    46.    54.    62.     0.65   0.66
    0.67   0.68   0.69]
 [  7.    15.   -99.   -99.   -99.    47.    55.   -99.     0.7    0.71
    0.72   0.73   0.74]
 [  8.    16.    24.   -99.    40.    48.    56.    64.     0.75   0.76
    0.77   0.78   0.79]]
(8, 13)


In [322]:
prom = np.zeros((13))
for i in range(C.shape[1]):
  prom[i] = np.mean(C[:,i])
  
print(prom)

[ -8.25   -1.5     5.25  -20.25  -81.625  26.75   33.5    40.25    0.575
   0.585   0.595   0.605   0.615]


In [323]:
D = np.insert(C, [8], prom, axis=0)
print(D)
print(D.shape)

[[  1.      9.     17.     25.    -99.     41.     49.     57.      0.4
    0.41    0.42    0.43    0.44 ]
 [  2.     10.     18.     26.    -99.     42.     50.     58.      0.45
    0.46    0.47    0.48    0.49 ]
 [-99.     11.     19.     27.    -99.    -99.     51.     59.      0.5
    0.51    0.52    0.53    0.54 ]
 [  4.     12.     20.     28.    -99.     44.     52.     60.      0.55
    0.56    0.57    0.58    0.59 ]
 [  5.    -99.     21.     29.    -99.     45.    -99.     61.      0.6
    0.61    0.62    0.63    0.64 ]
 [  6.     14.     22.    -99.    -99.     46.     54.     62.      0.65
    0.66    0.67    0.68    0.69 ]
 [  7.     15.    -99.    -99.    -99.     47.     55.    -99.      0.7
    0.71    0.72    0.73    0.74 ]
 [  8.     16.     24.    -99.     40.     48.     56.     64.      0.75
    0.76    0.77    0.78    0.79 ]
 [ -8.25   -1.5     5.25  -20.25  -81.625  26.75   33.5    40.25    0.575
    0.585   0.595   0.605   0.615]]
(9, 13)


In [324]:
max = np.zeros((9))
for i in range(D.shape[0]):
  max[i] = np.max(D[i,:])
  
print(max)
print(max.shape)

[57.   58.   59.   60.   61.   62.   55.   64.   40.25]
(9,)


In [325]:
R = np.insert(D.T, [13], max, axis=0).T
print(R)
print(R.shape)

[[  1.      9.     17.     25.    -99.     41.     49.     57.      0.4
    0.41    0.42    0.43    0.44   57.   ]
 [  2.     10.     18.     26.    -99.     42.     50.     58.      0.45
    0.46    0.47    0.48    0.49   58.   ]
 [-99.     11.     19.     27.    -99.    -99.     51.     59.      0.5
    0.51    0.52    0.53    0.54   59.   ]
 [  4.     12.     20.     28.    -99.     44.     52.     60.      0.55
    0.56    0.57    0.58    0.59   60.   ]
 [  5.    -99.     21.     29.    -99.     45.    -99.     61.      0.6
    0.61    0.62    0.63    0.64   61.   ]
 [  6.     14.     22.    -99.    -99.     46.     54.     62.      0.65
    0.66    0.67    0.68    0.69   62.   ]
 [  7.     15.    -99.    -99.    -99.     47.     55.    -99.      0.7
    0.71    0.72    0.73    0.74   55.   ]
 [  8.     16.     24.    -99.     40.     48.     56.     64.      0.75
    0.76    0.77    0.78    0.79   64.   ]
 [ -8.25   -1.5     5.25  -20.25  -81.625  26.75   33.5    40.25    0.575
  

In [326]:
np.savetxt('resulatdo.csv', R)

In [327]:
import pandas as pd

df = pd.DataFrame(R)
df

0     1      2      3       4      5     6      7      8      9      10  \
0   1.00   9.0  17.00  25.00 -99.000  41.00  49.0  57.00  0.400  0.410  0.420   
1   2.00  10.0  18.00  26.00 -99.000  42.00  50.0  58.00  0.450  0.460  0.470   
2 -99.00  11.0  19.00  27.00 -99.000 -99.00  51.0  59.00  0.500  0.510  0.520   
3   4.00  12.0  20.00  28.00 -99.000  44.00  52.0  60.00  0.550  0.560  0.570   
4   5.00 -99.0  21.00  29.00 -99.000  45.00 -99.0  61.00  0.600  0.610  0.620   
5   6.00  14.0  22.00 -99.00 -99.000  46.00  54.0  62.00  0.650  0.660  0.670   
6   7.00  15.0 -99.00 -99.00 -99.000  47.00  55.0 -99.00  0.700  0.710  0.720   
7   8.00  16.0  24.00 -99.00  40.000  48.00  56.0  64.00  0.750  0.760  0.770   
8  -8.25  -1.5   5.25 -20.25 -81.625  26.75  33.5  40.25  0.575  0.585  0.595   

      11     12     13  
0  0.430  0.440  57.00  
1  0.480  0.490  58.00  
2  0.530  0.540  59.00  
3  0.580  0.590  60.00  
4  0.630  0.640  61.00  
5  0.680  0.690  62.00  
6  0.730  0.740  55.00  
7  0.780  0.790  64.00  
8  0.605  0.615  40.25